CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  title VARCHAR(255),
  body TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  view_count INT DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE Comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  post_id INT,
  user_id INT,
  comment TEXT,
  created_at DATETIME,
  FOREIGN KEY (post_id) REFERENCES Posts(id),
  FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE Categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE Post_Categories (
  post_id INT,
  category_id INT,
  FOREIGN KEY (post_id) REFERENCES Posts(id),
  FOREIGN KEY (category_id) REFERENCES Categories(id)
);

CREATE TABLE Tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE Post_Tags (
  post_id INT,
  tag_id INT,
  FOREIGN KEY (post_id) REFERENCES Posts(id),
  FOREIGN KEY (tag_id) REFERENCES Tags(id)
);

CREATE TABLE SiteActivity (
  id INT AUTO_INCREMENT PRIMARY KEY,
  activity_type VARCHAR(255),
  description TEXT,
  created_at DATETIME
);
