name: Test AWS Credentials

on: [push]

jobs:
  test-aws-credentials:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_S3 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}
        aws-region: 'ap-southeast-2'
        
    - name: List S3 buckets
      run: aws s3 ls
