name: Deploy to S3

on:
  push:
    branches:
      - frontend  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: yarn install

    - name: Build Vue.js app
      run: yarn build

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --follow-symlinks --delete
      env:
        VUE_APP_BACKEND_URL: ${{ secrets.VUE_APP_BACKEND_URL }}
        AWS_S3_BUCKET: wjcblogs.com
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_S3}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3}}
        AWS_REGION: 'ap-southeast-2'
        SOURCE_DIR: 'dist'
